# Generated by Django 2.1 on 2019-08-28 11:44

import apps.form
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=0)),
                ('image_url', models.URLField(error_messages={'required': '请上传图片'})),
                ('link_to', models.URLField(error_messages={'invalid': '请设置正确的链接格式', 'required': '请设置跳转链接'})),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-priority', '-pub_time'],
            },
            bases=(models.Model, apps.form.FormMixin),
        ),
    ]
